apiVersion: 1

datasources:
  - name: Azure
    type: grafana-azure-monitor-datasource
    orgId: 1
    typeLogoUrl: public/plugins/grafana-azure-monitor-datasource/img/logo.jpg
    access: proxy
    isDefault: true
    jsonData:
      cloudName: azuremonitor
      subscriptionId: $SUBSCRIPTION_ID 
      tenantId: $TENANT_ID
      clientId: $CLIENT_ID
      azureLogAnalyticsSameAs: false
      logAnalyticsClientId: $CLIENT_ID
      logAnalyticsDefaultWorkspace: $LOG_ANALYTICS_WORKSPACE
      logAnalyticsSubscriptionId: $SUBSCRIPTION_ID
      logAnalyticsTenantId: $TENANT_ID
      keepCookies: []
    secureJsonData:
      clientSecret: $CLIENT_SECRET
      logAnalyticsClientSecret: $CLIENT_SECRET
    editable: true