apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allowreadingazure
spec:
  volumes:
    - 'hostPath'
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  # Allowing pods to use Azure
  allowedHostPaths:
    - pathPrefix: "/etc/kubernetes/azure.json"
      readOnly: true # only allow read-only mounts