kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:unprivileged
  namespace: default
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  resourceNames: ['restricted']
  verbs: ['use']