name: Fabrikate Defs -> K8s Manifests 

on:
  push:
    paths:
    - 'fabrikate-defs/**'
    - '!fabrikate-defs/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : GITHUB CONTEXT
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }} 
      run: echo "$GITHUB_CONTEXT" 

    - name: get commit message
      run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
    
    - name: Install Helm
      run: |
        curl -LO https://git.io/get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Download Bedrock orchestration script
      run: |
        curl $BEDROCK_BUILD_SCRIPT > build.sh
        chmod +x ./build.sh
      env:
        BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

    - name: Fabrikate defs -> k8s manifests
      run: |
        ./build.sh
      env:
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_MESSAGE: ${{ env.commitmsg }}
        REPO: https://github.com/sachinkundu/k8smanifests.git
        BRANCH_NAME: ${{ github.ref }}
        FAB_ENVS: dev
